name: WASM

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasm_build_and_test:
    runs-on: ubuntu-x86-8cpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup show

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-wasm-

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build WASM
        run: cargo build -p kontor-crypto-wasm --target wasm32-unknown-unknown --release

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test WASM
        run: wasm-pack test --node crates/kontor-crypto-wasm
